* segragate 词根
greg= group, flock, to collect 组, 群；收集
- aggregate v. 合计；聚集
ag 加强 + greg 组，群；收集 + ate 做，造成，使… → 加强组群 → 聚集
- congregate v. 聚集
con 加强 + greg 组，群；收集 + ate 做，造成，使… → 聚集
- desegregate v. 废止种族隔离
de 去掉 + segregate 使隔离 → 废止种族隔离
- desegregation n. 废止种族隔离
- desegregate的名词

disaggregate v. 分解；分离

dis 分离 + aggregate 聚集 → 将聚集的东西分离 → 分解

egregious adj. 过分的；不寻常的

e 出 + greg 组，群；收集 + ious …的 → 脱离团体的 → 不寻常的

gregarious adj. 群居的；爱社交的

greg 组，群；收集 + arious …的 → 爱群体的 → 群居的

segregate v. 分开，隔离

se 分开 + greg 组，群；收集 + ate 做，造成，使… → 和群体分开 → 隔离

segregation n. （种族）隔离

segregate的名词

前缀
se- 分开, 离开
secede v. 正式退出（组织）

se 分开，离开 + ced 走 + e → 走开 → 正式退出

secern v. 区别；分开

se 分开，离开 + cern 搞清，区别 → 区别；分开

secession n. 退出；脱离

secede的名词

seclude v. 隔离；隐居

se 分开，离开 + clud 关闭 + e → 离开并关闭起来 → 隔离

seclusion n. 隔离；归隐

seclude的名词

secrete v. 藏匿

se 分开，离开 + cret 产生 + e →〔悄悄离开〕使产生分离 → 藏匿

seduce v. 勾引，诱惑

se 分开，离开 + duc 引导 + e → 引开 → 勾引〔别人〕

segregate v. 隔离

se 分开，离开 + greg 群体 + ate 使… → 使和人群分开 → 隔离

select v. 选择

se 分开，离开 + lect 选择 → 选择

* todos
- cruft/crufty
- compartmentalize / compartment
- spiral
- arrogance
- memorization / memorize
- watch out
- blast
- legitimate
- erroneously
- contraction /extract
- propensity
- discern
- stamen / stamina
- obliquely


vaccination
proliferation
detrimental

- rudimentary
英/ ˌruːdɪˈmentri /美/ ˌruːdɪˈmentri /
Some dinosaurs had only rudimentary teeth.
有些恐龙只有未充分长成的牙齿。

- 20221026
-- confront with使面临 ; 使面对 ; 以…面对
Worse,many allocators exhibit a dramatic increase in memory consump-tion when confronted with a producer-consumer pattern of objectallocation and freeing.

- misnomer
- Circulating Supply 流通供应
circulate 流通
Leave a gap at the top and bottom so air can circulate

6. Learn ALL 44 English phonemes in 10 minutes!!! | 麦克老师
